apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Base dizinindeki kaynakları kullan
resources:
- ../../base
namePrefix: dev-
namespace: dev
images:
  - name: miraccan/servicename
    newTag: 1.0.7  # Dev ortamında kullanılacak image tag'i
# Dev ortamına özgü yamalar (patch)
# Dev ortamına özel ConfigMap ve Secret (opsiyonel)
configMapGenerator:
- literals:
  - ENV=dev
  - LOG_LEVEL=debug
  name: app-config
secretGenerator:
- literals:
  - API_KEY=dev-secret-key
  name: app-secret
patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml
